### ISSUE TITLE
blocks with lines vanished

### ISSUE THREAD

**Issue by carlosoliboniamigo** [MapperTV/roadstuff#13]
When I upgraded from 2.0.6.0 to 2.0.7.0 my blocks with lines changed in the world I had previously used them and when trying to get the blocks while in creative mode, they don't show up anymore in the inventory

**Comment by MapperTV** [comment]
The blocks were removed but only as item form. Actual blocks are still here. I removed the items because they were starting to be quite expensive in terms of data and were not that useful with the paintbrush being an easier way to paint roads. Plus, for Just Enough Item users, they were filling the block list too much and was annoying. Since I plan to add even more blocks in the future, it was getting too heavy. You need to use the paintbrush to create roads, it works in creative mode too and you do not need to refill the paint (except the first time to assign a color).

As for changed lines in the world, this is due to an update that added more line patterns and their ID changed a bit which caused this. You'll have to repaint your roads to fix them. Since the mod is now out of alpha, this won't happen anymore (I took the opportunity to exit alpha with reorganizing the patterns one last time). Sorry for the inconvenience but that was the reason the mod was still in alpha until now.
