### ISSUE TITLE
How to make a smooth turn?

### ISSUE THREAD

**Issue by carlosoliboniamigo** [MapperTV/roadstuff#14]
Hello,

I am having a hard time trying to find the right combination of patterns to make a smooth turn, small or large doesn't really matter, seems every combination I try ends up looking terrible...

Thanks in advance!

**Comment by MapperTV** [comment]
If you mean the different curve lines, you usually find the 4 packed together in the pattern selection. For example, patterns 9, 10, 11 and 12 (with the pattern 2 between) allows this curve:

![2019-10-14_16 08 08](https://user-images.githubusercontent.com/11135018/66757802-39e38900-ee9d-11e9-9463-1eda498245b1.png)

This is the most smooth curve you can paint. For larger curves, you'll have to use the diagonal line (pattern 2) or you can just make smooth sharp curves. Some examples here.

![2019-10-14_16 10 47](https://user-images.githubusercontent.com/11135018/66757809-3cde7980-ee9d-11e9-9a6a-0deb9736a731.png)

Remember this is Minecraft, so you'll naturally tend to make sharp curves (using diagonal or 90° corners) because of the block system. Even if I added those smooth curves, you'll always be kinda limited. I would need to add way more pattern for larger smooth curves, which is not in my plans at all as this would increase loading time and mod weight so much and I want to avoid that considering I'm planning to add more road surfaces later (one surface needs around 1300 blocks, slopes included, which need 10,000+ blockstates that need to be baked at loading).

**Comment by carlosoliboniamigo** [comment]
Thank you very much! The first example is what I was looking for. 
I managed to use the 90° corners but wasn't finding how to make the transition smooth. :)
