### ISSUE TITLE
Optifine incompatibility 1.14.4

### ISSUE THREAD

**Issue by NightScale5755** [MapperTV/roadstuff#16]
**FILL THIS!**
• Minecraft version: 1.14.4
• Forge version: 1.14.4 - 28.1.70
• Road Stuff version: roadstuff-1.14.4-2.0.9.0.jar
• Other mods used or modpack: OptiFine 1.14.4 HD U F4

**Describe the bug**
Explain what is the bug and how to reproduce it if you know. Give all details you can, like "broke this block using this item from this mod" etc.
When I use Optifine, and try to paint a slope with the paintbrush. It won't render. But the full blocks render fine. I don't know why this would happen, but it does. 
A fix would be a life saver!

![image](https://user-images.githubusercontent.com/43540281/67708427-26025180-f98a-11e9-820a-423f1b2371e3.png)

**Comment by MapperTV** [comment]
No idea how to fix this. I just use regular JSON renders so it probably comes from Optifine which is likely to have issues with mods sadly. I'll try to see with them.

**Comment by MapperTV** [comment]
I did some minor changes to the block models to attempt a fix. For now it seems to work. Apparently Optifine doesn't like when two faces are stacked and decides to "optimize" the model by removing one of them. Since my road blocks have two faces (one for the base material, like the asphalt and another one for the painted line using a transparent texture) to avoid making thousands of textures, Optifine attempted some optimization by removing the paint face. Not sure why it only happens on slope blocks. When I'll publish the next patch, you can try and confirm if it's fixed.

**Comment by NightScale5755** [comment]
So. 
I built your source code. And the patch works!
![image](https://user-images.githubusercontent.com/43540281/68074167-2cb40e80-fd66-11e9-8f39-e68fa6b09912.png)

**Comment by MapperTV** [comment]
Ok I released the build. Thanks for trying out!
